Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

function New-PathRow($parent, $label, $initial, $browseAction) {
  $p = New-Object System.Windows.Forms.Panel; $p.Dock='Top'; $p.Height=35; $parent.Controls.Add($p)
  $l = New-Object System.Windows.Forms.Label; $l.Text=$label; $l.Location='0,8'; $l.Size='120,22'; $p.Controls.Add($l)
  $box = New-Object System.Windows.Forms.TextBox; $box.Text=$initial; $box.Location='120,5'; $box.Size='590,25'; $box.Anchor='Top,Left,Right'; $p.Controls.Add($box)
  $b = New-Object System.Windows.Forms.Button; $b.Text='Choose folder...'; $b.Location='690,4'; $b.Size='115,26'; $b.Anchor='Top,Right'; $b.Add_Click({ & $browseAction $box }); $p.Controls.Add($b)
  return $box
}
function Choose-Folder($box) { $d=New-Object System.Windows.Forms.FolderBrowserDialog; $d.Description='Choose any folder on this PC'; $d.ShowNewFolderButton=$true; if(Test-Path -LiteralPath $box.Text -PathType Container){$d.SelectedPath=$box.Text}; if($d.ShowDialog() -eq 'OK'){$box.Text=$d.SelectedPath} }
function New-Grid($parent, [string[]]$names) {
  $g=New-Object System.Windows.Forms.DataGridView; $g.Dock='Fill'; $g.AutoGenerateColumns=$false; $g.AllowUserToAddRows=$false; $g.ReadOnly=$true; $g.SelectionMode='FullRowSelect'; $g.MultiSelect=$true; $g.AutoSizeColumnsMode='Fill'; $g.RowHeadersVisible=$false
  foreach($name in $names){$c=New-Object System.Windows.Forms.DataGridViewTextBoxColumn; $c.HeaderText=$name; [void]$g.Columns.Add($c)}; $parent.Controls.Add($g); return $g
}
function Get-UniquePath($path) { if(!(Test-Path -LiteralPath $path)){return $path}; $dir=[IO.Path]::GetDirectoryName($path); $stem=[IO.Path]::GetFileNameWithoutExtension($path); $ext=[IO.Path]::GetExtension($path); $n=1; do {$candidate=Join-Path $dir "$stem ($n)$ext"; $n++} while(Test-Path -LiteralPath $candidate); return $candidate }
function Show-Error($message){ [void][Windows.Forms.MessageBox]::Show($message,'FileTidy',[Windows.Forms.MessageBoxButtons]::OK,[Windows.Forms.MessageBoxIcon]::Error) }

$form=New-Object System.Windows.Forms.Form; $form.Text='FileTidy'; $form.Size='920,660'; $form.MinimumSize='760,520'; $form.StartPosition='CenterScreen'; $form.Font=New-Object Drawing.Font('Segoe UI',9)
$title=New-Object System.Windows.Forms.Label; $title.Text='FileTidy'; $title.Font=New-Object Drawing.Font('Segoe UI',18,[Drawing.FontStyle]::Bold); $title.Location='18,12'; $title.AutoSize=$true; $form.Controls.Add($title)
$sub=New-Object System.Windows.Forms.Label; $sub.Text='Choose any folder on your PC to organize files, rename batches, or find exact duplicates.'; $sub.Location='20,49'; $sub.AutoSize=$true; $form.Controls.Add($sub)
$tabs=New-Object System.Windows.Forms.TabControl; $tabs.Location='18,78'; $tabs.Size='865,530'; $tabs.Anchor='Top,Bottom,Left,Right'; $form.Controls.Add($tabs)

# Cleaner
$cleanTab=New-Object System.Windows.Forms.TabPage('Downloads Cleaner'); $tabs.TabPages.Add($cleanTab); $cleanTop=New-Object System.Windows.Forms.Panel; $cleanTop.Dock='Top'; $cleanTop.Height=104; $cleanTab.Controls.Add($cleanTop)
$downloads=[Environment]::GetFolderPath('UserProfile')+'\Downloads'; $cleanFolder=New-PathRow $cleanTop 'Folder to organize' $downloads ${function:Choose-Folder}
$archiveCheck=New-Object System.Windows.Forms.CheckBox; $archiveCheck.Text='Move files older than'; $archiveCheck.Location='120,40'; $archiveCheck.AutoSize=$true; $cleanTop.Controls.Add($archiveCheck)
$daysBox=New-Object System.Windows.Forms.NumericUpDown; $daysBox.Value=30; $daysBox.Minimum=1; $daysBox.Maximum=9999; $daysBox.Location='275,39'; $daysBox.Size='60,25'; $daysBox.Enabled=$false; $cleanTop.Controls.Add($daysBox)
$archiveCheck.Add_CheckedChanged({$daysBox.Enabled=$archiveCheck.Checked})
$oldLabel=New-Object System.Windows.Forms.Label; $oldLabel.Text='days into an Archive folder'; $oldLabel.Location='340,43'; $oldLabel.AutoSize=$true; $cleanTop.Controls.Add($oldLabel)
$cleanButtons=New-Object System.Windows.Forms.Panel; $cleanButtons.Dock='Bottom'; $cleanButtons.Height=42; $cleanTab.Controls.Add($cleanButtons); $cleanGrid=New-Grid $cleanTab @('File','Destination')
$cleanPreview=New-Object System.Windows.Forms.Button; $cleanPreview.Text='Preview changes'; $cleanPreview.Location='0,7'; $cleanPreview.Size='120,27'; $cleanButtons.Controls.Add($cleanPreview)
$cleanApply=New-Object System.Windows.Forms.Button; $cleanApply.Text='Organize files'; $cleanApply.Location='130,7'; $cleanApply.Size='110,27'; $cleanApply.Enabled=$false; $cleanButtons.Controls.Add($cleanApply); $cleanPlan=@()
$cleanPreview.Add_Click({
  try { $root=(Resolve-Path -LiteralPath $cleanFolder.Text -ErrorAction Stop).Path; $script:cleanPlan=@(); $cleanGrid.Rows.Clear(); $exts=@{Images='.jpg','.jpeg','.png','.gif','.bmp','.webp','.svg','.heic','.tiff'; Documents='.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.txt','.csv','.rtf','.odt'; Installers='.exe','.msi','.msix','.appx','.bat','.cmd'; Audio='.mp3','.wav','.flac','.m4a','.aac','.ogg','.wma'; Video='.mp4','.mkv','.avi','.mov','.wmv','.webm'; Archives='.zip','.rar','.7z','.tar','.gz','.bz2','.iso'}; $cutoff=(Get-Date).AddDays(-[int]$daysBox.Value)
    Get-ChildItem -LiteralPath $root -File | ForEach-Object { $cat='Other'; foreach($key in $exts.Keys){if($exts[$key] -contains $_.Extension.ToLower()){$cat=$key;break}}; if($archiveCheck.Checked -and $_.LastWriteTime -lt $cutoff){$cat='Archive'}; $target=Get-UniquePath (Join-Path (Join-Path $root $cat) $_.Name); $script:cleanPlan += [pscustomobject]@{Source=$_.FullName;Target=$target}; [void]$cleanGrid.Rows.Add($_.Name,($target.Substring($root.Length).TrimStart('\'))) }
    $cleanApply.Enabled=($cleanPlan.Count -gt 0)
  } catch { Show-Error $_.Exception.Message }
})
$cleanApply.Add_Click({ if([Windows.Forms.MessageBox]::Show("Move $($cleanPlan.Count) file(s) shown in the preview?",'Organize files','YesNo','Question') -ne 'Yes'){return}; $n=0; try {foreach($item in $cleanPlan){if(Test-Path -LiteralPath $item.Source){New-Item -ItemType Directory -Force -Path (Split-Path $item.Target) | Out-Null; Move-Item -LiteralPath $item.Source -Destination $item.Target; $n++}}; [void][Windows.Forms.MessageBox]::Show("Organized $n file(s).",'FileTidy')}catch{Show-Error "Moved $n file(s).`n$($_.Exception.Message)"}; $cleanPreview.PerformClick() })

# Renamer
$renameTab=New-Object System.Windows.Forms.TabPage('Bulk Renamer'); $tabs.TabPages.Add($renameTab); $renameTop=New-Object System.Windows.Forms.Panel; $renameTop.Dock='Top'; $renameTop.Height=140; $renameTab.Controls.Add($renameTop); $renameFolder=New-PathRow $renameTop 'Folder' '' ${function:Choose-Folder}
function Add-RenameControl($text,$x,$y,$width){$l=New-Object Windows.Forms.Label; $l.Text=$text; $l.Location="$x,$y"; $l.Size="$width,20"; $renameTop.Controls.Add($l); $b=New-Object Windows.Forms.TextBox; $b.Location="$($x+$width),$($y-3)"; $b.Size='190,25'; $renameTop.Controls.Add($b);return $b}
$prefixBox=Add-RenameControl 'Add prefix' 120 43 80; $findBox=Add-RenameControl 'Find text' 120 75 80; $replaceBox=Add-RenameControl 'Replace with' 120 107 80
$spacesCheck=New-Object Windows.Forms.CheckBox; $spacesCheck.Text='Replace spaces with dashes'; $spacesCheck.Checked=$true; $spacesCheck.Location='430,43'; $spacesCheck.AutoSize=$true; $renameTop.Controls.Add($spacesCheck)
$numberCheck=New-Object Windows.Forms.CheckBox; $numberCheck.Text='Number files sequentially'; $numberCheck.Location='430,75'; $numberCheck.AutoSize=$true; $renameTop.Controls.Add($numberCheck)
$renameButtons=New-Object Windows.Forms.Panel; $renameButtons.Dock='Bottom'; $renameButtons.Height=42; $renameTab.Controls.Add($renameButtons); $renameGrid=New-Grid $renameTab @('Current name','New name'); $renamePreview=New-Object Windows.Forms.Button; $renamePreview.Text='Preview rename'; $renamePreview.Location='0,7'; $renamePreview.Size='120,27'; $renameButtons.Controls.Add($renamePreview); $renameApply=New-Object Windows.Forms.Button; $renameApply.Text='Rename files'; $renameApply.Location='130,7'; $renameApply.Size='110,27'; $renameApply.Enabled=$false; $renameButtons.Controls.Add($renameApply); $renamePlan=@()
$renamePreview.Add_Click({try{$root=(Resolve-Path -LiteralPath $renameFolder.Text -ErrorAction Stop).Path;$files=@(Get-ChildItem -LiteralPath $root -File | Sort-Object Name);$script:renamePlan=@();$renameGrid.Rows.Clear();$names=@{};$i=0;foreach($file in $files){$i++;$stem=$file.BaseName;if($spacesCheck.Checked){$stem=$stem -replace '\s+','-'};if($findBox.Text){$stem=$stem.Replace($findBox.Text,$replaceBox.Text)};$stem=$prefixBox.Text+$stem;if($numberCheck.Checked){$stem='{0:D3}-{1}' -f $i,$stem};$new=$stem+$file.Extension;if($names.ContainsKey($new.ToLower())){throw "These settings create duplicate names: $new"};$names[$new.ToLower()]=$true;$target=Join-Path $root $new;if($target -ne $file.FullName){$script:renamePlan += [pscustomobject]@{Source=$file.FullName;Target=$target};[void]$renameGrid.Rows.Add($file.Name,$new)}};$renameApply.Enabled=($renamePlan.Count -gt 0)}catch{Show-Error $_.Exception.Message}})
$renameApply.Add_Click({if([Windows.Forms.MessageBox]::Show("Rename $($renamePlan.Count) file(s) shown in the preview?",'Rename files','YesNo','Question') -ne 'Yes'){return};try{$temp=@();$i=0;foreach($item in $renamePlan){$i++;$tmp=Join-Path (Split-Path $item.Source) ".__filetidy_$i";Move-Item -LiteralPath $item.Source -Destination $tmp;$temp += [pscustomobject]@{Source=$tmp;Target=$item.Target}};foreach($item in $temp){Move-Item -LiteralPath $item.Source -Destination $item.Target};[void][Windows.Forms.MessageBox]::Show("Renamed $($renamePlan.Count) file(s).",'FileTidy');$renamePreview.PerformClick()}catch{Show-Error $_.Exception.Message}})

# Duplicate finder
$dupeTab=New-Object Windows.Forms.TabPage('Duplicate Finder'); $tabs.TabPages.Add($dupeTab); $dupeTop=New-Object Windows.Forms.Panel; $dupeTop.Dock='Top'; $dupeTop.Height=42; $dupeTab.Controls.Add($dupeTop); $dupeFolder=New-PathRow $dupeTop 'Folder to scan' '' ${function:Choose-Folder}; $dupeBottom=New-Object Windows.Forms.Panel; $dupeBottom.Dock='Bottom'; $dupeBottom.Height=66; $dupeTab.Controls.Add($dupeBottom); $dupeGrid=New-Grid $dupeTab @('Keep / duplicate file','Size'); $scan=New-Object Windows.Forms.Button; $scan.Text='Scan for duplicates'; $scan.Location='0,5';$scan.Size='135,27';$dupeBottom.Controls.Add($scan);$remove=New-Object Windows.Forms.Button;$remove.Text='Move selected duplicates to Recycle Bin';$remove.Location='145,5';$remove.Size='230,27';$remove.Enabled=$false;$dupeBottom.Controls.Add($remove);$status=New-Object Windows.Forms.Label;$status.Text='Files are compared by MD5 content hash. The first result in each group is marked KEEP.';$status.Location='0,37';$status.AutoSize=$true;$dupeBottom.Controls.Add($status);$dupeGroups=@()
$scan.Add_Click({try{$root=(Resolve-Path -LiteralPath $dupeFolder.Text -ErrorAction Stop).Path;$dupeGrid.Rows.Clear();$script:dupeGroups=@();$status.Text='Scanning files… this may take a while for large folders.';$form.Refresh();$bySize=@{};Get-ChildItem -LiteralPath $root -File -Recurse -ErrorAction SilentlyContinue|ForEach-Object{$size=$_.Length;if(!$bySize.ContainsKey($size)){$bySize[$size]=@()};$bySize[$size]+=$_.FullName};foreach($files in $bySize.Values){if($files.Count -lt 2){continue};$byHash=@{};foreach($path in $files){try{$h=(Get-FileHash -LiteralPath $path -Algorithm MD5).Hash;if(!$byHash.ContainsKey($h)){$byHash[$h]=@()};$byHash[$h]+=$path}catch{}};foreach($group in $byHash.Values){if($group.Count -gt 1){$script:dupeGroups += ,$group}}};$copies=0;foreach($group in $dupeGroups){for($i=0;$i -lt $group.Count;$i++){$p=$group[$i];$label=if($i -eq 0){'KEEP  '}else{$copies++;'DUPLICATE  '};$size='{0:N2} MB' -f ((Get-Item -LiteralPath $p).Length/1MB);$row=$dupeGrid.Rows.Add($label+$p,$size);$dupeGrid.Rows[$row].Tag=if($i -eq 0){'KEEP'}else{$p}}};$remove.Enabled=($copies -gt 0);$status.Text="Found $($dupeGroups.Count) duplicate group(s), $copies removable copy/copies. Select only DUPLICATE rows."}catch{Show-Error $_.Exception.Message}})
$remove.Add_Click({$chosen=@($dupeGrid.SelectedRows|ForEach-Object{$_.Tag}|Where-Object{$_ -and $_ -ne 'KEEP'});if(!$chosen){[void][Windows.Forms.MessageBox]::Show('Select one or more rows marked DUPLICATE first.','FileTidy');return};if([Windows.Forms.MessageBox]::Show("Move $($chosen.Count) selected file(s) to the Windows Recycle Bin?",'Move to Recycle Bin','YesNo','Question') -ne 'Yes'){return};$failed=@();foreach($p in $chosen){try{Add-Type -AssemblyName Microsoft.VisualBasic;[Microsoft.VisualBasic.FileIO.FileSystem]::DeleteFile($p,'OnlyErrorDialogs','SendToRecycleBin')}catch{$failed+=$p}};if($failed.Count){Show-Error "Could not move $($failed.Count) file(s)."}else{[void][Windows.Forms.MessageBox]::Show("Moved $($chosen.Count) file(s) to the Recycle Bin.",'FileTidy')};$scan.PerformClick()})

[void]$form.ShowDialog()
